### ISSUE TITLE
REQUEST: Beam Avatars beside user's name in chat

### ISSUE THREAD

**Issue by bohl3r** [ExuDev/ExuPro#1]
I would like to see you guys add a avatar feature to show a avatar beside the user's name in chat. I've made my own code in HTML with this, you could fiddle with it and make it better.

##### Here is a preview of my code and an example of what the chat would look like.
![Preview of Output](http://imgwiz.com/images/2015/02/21/C87TH.png)

```html
<div id="chatmessage-b696df30-ba48-11e4-ac20-eb690f57496f" class="message" data-role="User">
    <div class="message-author" data-message="b696df30-ba48-11e4-ac20-eb690f57496f">
        <span><img src="https://s3.amazonaws.com/uploads.beam.pro/avatars/212-256x256.jpg?v=0" alt="avatar" height="25px" width="25px">&nbsp;</span>Keith
    </div>
    <div class="message-body">Enter Message Here</div>
</div>
```

**Comment by Exuviax** [comment]
Awesome! What kind of avatars would we be grabbing? The users avatar or a Gravitar?

**Comment by bohl3r** [comment]
I would have to say the avatar from Beam, just to keep it connected with Beam and not have to have an email from the user.

**Comment by Exuviax** [comment]
Sound good, we will look into it! I am going to close this issue since I checked it! But I will respond here if we decide to do this!

**Comment by bohl3r** [comment]
Sounds good.
